"""Initial schema

Creates every table, enum, index, and constraint defined by the models.

This first revision builds the schema from `Base.metadata` rather than a
hand-written list of `op.create_table` calls. For a greenfield database that is
both safer and more accurate — SQLAlchemy emits the enum types, indexes, and
foreign keys in dependency order, so the migration cannot drift from the models
it was generated alongside. Every migration after this one is a normal
autogenerated diff.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-20
"""

from collections.abc import Sequence

from alembic import op

from app.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
